In [1]:
import numpy as np
import pandas as pd
from PIL import Image
import os

In [2]:
label = pd.read_csv('train.csv')
label.keys()

Index(['name', 'square', 'circle', 'triangle'], dtype='object')

In [3]:
square = label['square']

In [4]:
# iam = Image.open('.\custom_images\hackthoon308train00000.jpg')
# iam = np.array(iam,dtype = 'float32')/255
# tuple(iam[4][:][:])

In [5]:
# imagedata = np.empty((8000,128,128,3))
# imagedata.shape

# path = r'.\custom_images'
# filenames = os.listdir(path)
# i = 0
# for file in filenames:
#     temp = Image.open(os.path.join(path,file))
#     temp = np.array(temp)
#     imagedata[i,:,:,:] = temp
#     np.append(imagedata,temp)
#     i = i + 1 

In [12]:
path = r'.\custom_images'
filenames = os.listdir(path)
imgdata = []
for file in filenames:
    temp = Image.open(os.path.join(path,file))
    temp = np.array(temp)
    # print(temp.shape)
    imgdata = imgdata + [temp]
imgdata = np.array(imgdata)

(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 

In [10]:
imgdata.shape

(8000, 128, 128, 3)

In [7]:
imgdata = (imgdata.reshape(imgdata.shape[0],imgdata.shape[1]*imgdata.shape[2]*imgdata.shape[3]))

In [8]:
imgdata.shape

(8000, 49152)

In [8]:
# test = pd.DataFrame(imagedata)
# tuple(imgdata.shape)
imgdata[0]

array([1, 1, 1, ..., 1, 1, 1], dtype=uint8)

In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [10]:
X_train, X_test, y_train, y_test = train_test_split(imgdata, square, test_size=0.3, random_state=123)

In [11]:
# type(X_train)
X_train.shape

(5600, 49152)

### 决策树

In [12]:
model1 = DecisionTreeClassifier()
# model2 = RandomForestClassifier(random_state=123,n_estimators=60)
model1.fit(X_train,y_train)
# model2.fit(X_train,y_train)

In [ ]:
score_filter1 = model1.score(X_test, y_test)
score_filter1

0.64625

In [ ]:
predictions = model1.predict(X_test)
predictions[:10]

array([1, 1, 1, 1, 0, 1, 0, 1, 0, 0], dtype=int64)

In [ ]:
pre = pd.DataFrame()
pre['prediction'] = predictions
pre['real'] = y_test
pre.head(100)
# 毫无准确率哈哈哈

prediction  real
0            1   NaN
1            1   NaN
2            1   NaN
3            1   NaN
4            0   1.0
..         ...   ...
95           0   1.0
96           1   NaN
97           1   1.0
98           1   0.0
99           1   NaN

[100 rows x 2 columns]

In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy:%s'% accuracy_score(y_test,predictions))

Accuracy:0.64625


In [ ]:
y_test.shape

(2400,)

### RF

In [ ]:
model2 = RandomForestClassifier(random_state=123,n_estimators=60)
model2.fit(X_train,y_train)

RandomForestClassifier(n_estimators=60, random_state=123)

In [ ]:
score_filter2 = model2.score(X_test, y_test)
score_filter2

0.7266666666666667

In [ ]:
predictions2 = model2.predict(X_test)
predictions2[:10]

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
# 转一下，不然可能会出现下标错误
y_test = np.array(y_test)

pre2 = pd.DataFrame()
pre2['prediction'] = predictions2
pre2['real'] = y_test
pre2.head(100)

prediction  real
0            1     1
1            1     1
2            1     1
3            1     1
4            0     1
..         ...   ...
95           0     0
96           1     0
97           0     1
98           1     0
99           1     1

[100 rows x 2 columns]

In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy:%s'% accuracy_score(y_test,predictions2))

Accuracy:0.7266666666666667


### logic R

In [ ]:
model3 = LogisticRegression()
model3.fit(X_train,y_train)

D:\pythonenvs\testkeras\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [ ]:
score_filter3 = model3.score(X_test, y_test)
score_filter3

0.6220833333333333