In [3]:
import numpy as np
x=np.arange(5)
y=np.arange(5,10)
z=np.arange(5,10,0.5)
print(x)
print(y)
print(z)

[0 1 2 3 4]
[5 6 7 8 9]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [6]:
# pandas 中 series:一维列表
import pandas as pd
s1=pd.Series(['丁1','王二','张三'])
print(s1)

0    丁1
1    王二
2    张三
dtype: object


In [9]:
# pandas 中 DataFrame：二维列表
import pandas as pd
s1=pd.DataFrame([[1,2],[3,4],[5,6]],columns=['date','score'],index=['A','B','C'])
print(s1)

   date  score
A     1      2
B     3      4
C     5      6


In [10]:
a=pd.DataFrame()
data=[1,3,5]
score=[2,4,6]
a['data']=data
a['score']=score
print(a)

   data  score
0     1      2
1     3      4
2     5      6


In [13]:
# 通过字典创建dataframe
pd.DataFrame({'a':[1,3,5],'b':[2,4,6]},index=['x','y','z'])

a  b
x  1  2
y  3  4
z  5  6

In [22]:
# 翻转字典值
pd.DataFrame({'a':[1,3,5],'b':[2,4,6]},index=['x','y','z'])


AttributeError: module 'pandas' has no attribute 'set_index'

In [1]:
print(12+2)

14
