In [37]:
# 逻辑预测
# 自行构造数据训练模型
X = [[1,0],[5,1],[6,4],[4,2],[3,2]]
y = [0,1,1,0,0]

# 训练模型
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [38]:
# 消除FutureWarning警告信息
import warnings
warnings.filterwarnings('ignore')

In [39]:
# 预测1
print(model.predict([[2,2]]))

[0]


In [40]:
# 预测2
print(model.predict([[1,1],[2,2],[5,5]]))

[0 0 1]


In [41]:
# 原始数据预测，准确率为百分百
print(model.predict([[1,0],[5,1],[6,4],[4,2],[3,2]]))

[0 1 1 0 0]


In [42]:
# 预测概率：左为分类为0的概率，右为分类为1的概率
y_pred_proba = model.predict_proba(X)
print(y_pred_proba)

[[0.97344854 0.02655146]
 [0.39071972 0.60928028]
 [0.17991028 0.82008972]
 [0.63167893 0.36832107]
 [0.82424527 0.17575473]]


In [43]:
# 使用pandas方式打印概率表
import pandas as pd
a = pd.DataFrame(y_pred_proba,columns=['分类为0的概率','分类为1的概率'])
a.head()

分类为0的概率   分类为1的概率
0  0.973449  0.026551
1  0.390720  0.609280
2  0.179910  0.820090
3  0.631679  0.368321
4  0.824245  0.175755

In [44]:
# 系数
print(model.coef_)
# 截距
print(model.intercept_)

[[1.00595248 0.02223835]]
[-4.60771284]


In [45]:
# 大写T表示矩阵转置
model.coef_.T

array([[1.00595248],
       [0.02223835]])

In [46]:
# 批量查看预测概率
import numpy as np
for i in range(2):
    print(1 / (1+np.exp(-(np.dot(X[i],model.coef_.T)+model.intercept_))))

[0.02655146]
[0.60928028]
